name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@v2.1.1

      - name: Install dependencies
        run: sudo apt-get install -y build-essential libgtest-dev clang-format

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: ./build/runTests

      - name: Check clang-format
        run: |
          clang-format -i $(find . -name '*.cpp' -o -name '*.hpp')
          git diff --exit-code
